// **********************************************************************
// Parsed By TarsParser(1.2.0), Generated By tars2node(20200315)
// TarsParser Maintained By <TARS> and tars2node Maintained By <superzheng>
// Generated from "DataBaseService.tars" by Structure Mode
// **********************************************************************

/* eslint-disable */

"use strict";

var assert    = require("assert");
var TarsStream = require("@tars/stream");

var _hasOwnProperty = Object.prototype.hasOwnProperty;

var RentHouse = RentHouse || {};
module.exports.RentHouse = RentHouse;

RentHouse.User = function() {
    this.name = "";
    this.gender = "";
    this.avatar_url = "";
    this.last_login_time = "";
    this.role = "";
    this._classname = "RentHouse.User";
};
RentHouse.User._classname = "RentHouse.User";
RentHouse.User._write = function (os, tag, value) { os.writeStruct(tag, value); };
RentHouse.User._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
RentHouse.User._readFrom = function (is) {
    var tmp = new RentHouse.User;
    tmp.name = is.readString(0, true, "");
    tmp.gender = is.readString(1, true, "");
    tmp.avatar_url = is.readString(2, true, "");
    tmp.last_login_time = is.readString(3, true, "");
    tmp.role = is.readString(4, true, "");
    return tmp;
};
RentHouse.User.prototype._writeTo = function (os) {
    os.writeString(0, this.name);
    os.writeString(1, this.gender);
    os.writeString(2, this.avatar_url);
    os.writeString(3, this.last_login_time);
    os.writeString(4, this.role);
};
RentHouse.User.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
RentHouse.User.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
RentHouse.User.prototype.toObject = function() { 
    return {
        "name" : this.name,
        "gender" : this.gender,
        "avatar_url" : this.avatar_url,
        "last_login_time" : this.last_login_time,
        "role" : this.role
    };
};
RentHouse.User.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "name") && (this.name = json.name);
    _hasOwnProperty.call(json, "gender") && (this.gender = json.gender);
    _hasOwnProperty.call(json, "avatar_url") && (this.avatar_url = json.avatar_url);
    _hasOwnProperty.call(json, "last_login_time") && (this.last_login_time = json.last_login_time);
    _hasOwnProperty.call(json, "role") && (this.role = json.role);
    return this;
};
RentHouse.User.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
RentHouse.User.new = function () {
    return new RentHouse.User();
};
RentHouse.User.create = function (is) {
    return RentHouse.User._readFrom(is);
};


