// **********************************************************************
// Parsed By TarsParser(1.2.0), Generated By tars2node(20200315)
// TarsParser Maintained By <TARS> and tars2node Maintained By <superzheng>
// Generated from "StatusCode.tars" by Structure Mode
// **********************************************************************

/* eslint-disable */

"use strict";


var RentHouse = RentHouse || {};
module.exports.RentHouse = RentHouse;

RentHouse.StatusCode = {
    "SUCCESS" : 200,
    "NOT_FOUND" : 404,
    "INTERNAL_ERROR" : 500,
    "USER_NOT_EXSIT" : 1001,
    "WRONG_PW_OR_NAME" : 1002,
    "USER_EXSIT" : 1003
};
RentHouse.StatusCode._classname = "RentHouse.StatusCode";
RentHouse.StatusCode._write = function(os, tag, val) { return os.writeInt32(tag, val); };
RentHouse.StatusCode._read  = function(is, tag, def) { return is.readInt32(tag, true, def); };


